import os
import json
import zipfile
import tempfile
import uuid
from typing import Dict, Any, List

class ProjectGenerator:
    """Generate downloadable project files from AI response"""
    
    @staticmethod
    def create_project_zip(project_data: Dict[str, Any]) -> str:
        """Create a ZIP file containing the generated project"""
        project_id = str(uuid.uuid4())
        
        # Create temporary directory for project files
        with tempfile.TemporaryDirectory() as temp_dir:
            project_dir = os.path.join(temp_dir, f"generated_project_{project_id}")
            os.makedirs(project_dir, exist_ok=True)
            
            # Create files from AI response
            for file_info in project_data.get("files", []):
                file_path = os.path.join(project_dir, file_info["path"])
                
                # Create directory structure
                os.makedirs(os.path.dirname(file_path), exist_ok=True)
                
                # Write file content
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(file_info["content"])
            
            # Create additional project files
            ProjectGenerator._create_additional_files(project_dir, project_data)
            
            # Create ZIP file
            zip_path = f"generated_projects/project_{project_id}.zip"
            os.makedirs(os.path.dirname(zip_path), exist_ok=True)
            
            with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
                for root, dirs, files in os.walk(project_dir):
                    for file in files:
                        file_path = os.path.join(root, file)
                        arcname = os.path.relpath(file_path, project_dir)
                        zipf.write(file_path, arcname)
            
            return zip_path
    
    @staticmethod
    def _create_additional_files(project_dir: str, project_data: Dict[str, Any]) -> None:
        """Create additional project files like README, scripts, etc."""
        
        # Create enhanced README
        readme_content = f"""# Generated Project by PromptCodeGen

This project was generated automatically based on your requirements.

## Instructions

{chr(10).join(f"- {instruction}" for instruction in project_data.get("instructions", []))}

## Commands to Run

{chr(10).join(f"```bash{chr(10)}{command}{chr(10)}```{chr(10)}" for command in project_data.get("commands", []))}

## Project Structure

Generated files:
{chr(10).join(f"- {file_info['path']}" for file_info in project_data.get("files", []))}

## Next Steps

1. Extract this ZIP file
2. Follow the instructions above
3. Customize the code as needed
4. Deploy your application

---
Generated by PromptCodeGen
"""
        
        readme_path = os.path.join(project_dir, "README.md")
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)
        
        # Create .env.example if backend files are present
        has_backend = any(file_info["path"].startswith("backend/") for file_info in project_data.get("files", []))
        
        if has_backend:
            env_example_content = """# Environment Variables
APP_ENV=dev
DATABASE_URL=sqlite:///./app.db
API_KEY=your_api_key_here
PORT=8000
"""
            env_path = os.path.join(project_dir, ".env.example")
            with open(env_path, 'w', encoding='utf-8') as f:
                f.write(env_example_content)